services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - cart-database:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - cart-network

  # Interface web para o mongo
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-interface
    restart: unless-stopped
    ports:
      - 27018:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - cart-network

#  cart-service:
#    image: cart-service:1.0.0
#    build:
#      dockerfile: Dockerfile
#    container_name: cart-service
#    ports:
#      - 7078:8080
#    depends_on:
#      - mongodb
#    restart: unless-stopped
#    env_file:
#      - .env
#    networks:
#      - cart-network

networks:
  cart-network:
    name: cart-network
  gateway-network:
    external: true
    name: ecommerce-network

volumes:
  cart-database: